ecommerce/cart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from cart import views

app_name='cart'

urlpatterns = [

    path('addtocart/<n>',views.addtocart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove/<n>',views.cart_remove,name="cart_remove"),
    path('cart_delete/<n>',views.cart_delete,name="cart_delete"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from search import views
app_name='search'


urlpatterns = [
    path('search',views.search,name="search"),

]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from shop import views
app_name="shop"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.allcategories,name="allcat"),
    path('allproducts/<p>',views.allproducts,name="allproducts"),
    path('detail/<p>',views.detail,name="detail"),
    path('userlogin', views.userlogin, name="userlogin"),
    path('register', views.register, name="register"),
    path('logout', views.userlogout, name="logout"),


]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.contrib.auth.models import User
from django.db import models

from shop.models import Product


# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    data_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity * self.product.price

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    no_of_items = models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    ordered_date = models.DateTimeField(auto_now_add=True)
    address=models.TextField()
    phone=models.IntegerField()
    ordered_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="Pending")

    def __str__(self):
        return self.product.name

class Account(models.Model):
    acctnum=models.IntegerField()
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()

    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render

from shop.models import Product

from cart.models import Cart, Account,Order




# Create your views here.
@login_required
def cartview(request):
    u = request.user
    cart = Cart.objects.filter(user=u)
    total = 0
    for i in cart:
        total += i.quantity * i.product.price

    return render(request, "cartview.html", {'c': cart, 'total': total})

@login_required
def addtocart(request, n):
    p = Product.objects.get(name=n)
    u = request.user  # current login user

    try:  # more one quantity undo ennu check chyn vendi function use chynm
        cart = Cart.objects.get(user=u, product=p)  # more one product or user undkil kodukn ulla condition
                                                     # if (cart.quantity < cart.product.stock):  # stock quantity vara maartme stock add chyn pattum quantity exceed aykth iriknm kodukunna cade  ulla function
        if(p.stock > 0):
            cart.quantity += 1  # more than one product undkil athu kood increment chyn ulla condition
            cart.save()
            p.stock -=1
            p.save()

    except:
        if (p.stock > 0):
            cart = Cart.objects.create(product=p, user=u, quantity=1)
            cart.save()
            p.stock -=1
            p.save()
    return cartview(request)

@login_required
def cart_remove(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)

        if (cart.quantity > 1):  # quantity teerumbo cartil irunnu delete ay poknm. athnu anu ee function kodukunne
            cart.quantity -= 1
            cart.save()
            p.stock +=1
            p.save()
        else:
            cart.delete()
            p.stock += 1
            p.save()
    except:
        pass

    return cartview(request)

@login_required
def cart_delete(request, n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        cart.delete()
        p.stock += cart.quantity
        p.save()

    except:
        pass
    return cartview(request)

@login_required
def orderform(request):
    if (request.method == "POST"):
        a = request.POST['a']
        p = request.POST['p']
        n = request.POST['n']

        u = request.user
        cart = Cart.objects.filter(user=u)

        total = 0
        for i in cart:
            total += i.quantity * i.product.price

        try:
            num = int(n)
            ac = Account.objects.get(acctnum=num)

            if (ac.amount >= total):
                ac.amount = ac.amount - total
                ac.save()
                #return HttpResponse(ac.amount)

                for i in cart:
                    o=Order.objects.create(user=u, product=i.product, address=a, phone=p, no_of_items=i.quantity,ordered_status="paid")
                    o.save()
                cart.delete()
                msg="Your order placed successfully"
                return render(request,'orderdetail.html',{'msg':msg})

            else:

                msg="Insufficient Amount.You can't Place Order"
                return render(request,'orderdetail.html',{'msg':msg})


        except:
            pass

    return render(request, 'orderform.html')


@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from django.db.models import Q
from django.shortcuts import render
from shop.models import Product


# Create your views here.

def search(request):
    query = ""
    b = None
    if request.method == "POST":
        query = request.POST.get('q', '')
        if query:
            b = Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))
    return render(request, "search.html", {'query': query, 'b': b})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond&family=Slabo+27px&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">     <!--static nte link koduknm-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
<header>
    <div class="container-fluid">
        <center><img src="{% static 'images/logo2.jpeg' %}" height="100px" width="100px"></center>
    </div>


<!--navbar-->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{i.name}}</a></li>
            {% endfor %}
          </ul>
        </li>

          {% if user.is_authenticated %}

          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>

          {% if user.is_superuser == False %}

          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"><sub class="ms-1">{{count}}</sub></i></a>
        </li>
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">Your Order</a>
        </li>
          {% endif %}


          {% else %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>

          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:userlogin' %}">Login</a>
        </li>

            {% endif %}
      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2"  name='q' type="search"  placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

</header>

{%block content %}

{% endblock %}


<footer>
        <div class="footer" style="border border-dark mt-3">
            <p><b> My Shop <i class="fa-regular fa-copyright"></i> pvt ltd. All rights Reserved</b></p>

        </div>

</footer>

<!--or this method-->

<!--<footer class="col-sm-12 border border-dark mt-3" style="height=100px; width:100%; background-color:lightgrey">-->

<!--        <p class="text-center text-color:black"><b> <i class="fa-solid fa-copyright"></i> My Shop pvt ltd. All rights Reserved</b></p>-->
<!--    </footer>-->


</body>
</html>

ecommerce/templates/cartview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom:100px;">
    <div class="row">
        <h4 class="text-center"> Shopping Cart</h4>

        <div class="col-7" >
            <table class="table table-bordered text-center fs-5">
            <tr>
                <th colspan="6">Cart Items</th>
            </tr>
                {% for i in c %}
                <tr>
                    <td><img src="{{i.product.image.url}}" height="150px" width="100px"></td>

                <td><p><b>{{i.product.name}}</b></p> </td>

                <td><b></b>ProductID:{{product.id}}</b><br>
                <b>Unit Price:{{i.product.price}}</b><br>
                <b>Quantity:{{i.quantity}}*{{i.product.price}}</b>
                    </td>

                    <td><b>Subtotal:{{i.subtotal}}</b></td>

                    <td>

                        {% if i.product.stock > 0 %}
                            <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-circle-plus text-success fs-4"></i></a>
                            <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-success fs-4"></i></a>
                            <a href="{% url 'cart:cart_delete' i.product.name %}"><i class="fa-solid fa-trash text-danger fs-4"></i></a>

                        {% else %}

                            <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-success fs-4"></i></a>
                            <a href="{% url 'cart:cart_delete' i.product.name %}"><i class="fa-solid fa-trash text-danger fs-4"></i></a>

                        {% endif %}
                    </td>

                    </tr>

                {% endfor %}


        </table></div>


        <div class="col-4 ms-3"style="position:relative;">
            <table class="table table-bordered">
            <tr>
                <th colspan="4">Check Out:</th>
            </tr>
                <tr>
                    <td>Total Amount:<span style="position:absolute;right:20px;">{{total}}</span></td>
                </tr>
        </table>
        <a href="{% url 'cart:orderform' %}"class="btn btn-danger">Place Order</a>
            <a href="{% url 'shop:allcat' %}"class="btn btn-danger" style="position:absolute;right:20px;">Continue Shopping</a>
        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--banner-->
<div class="container-fluid">
    <img src="{% static 'images/banner.jpeg' %}" height="450px" width="100%">
</div>

<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw bold">Our Collections</h3>
    <p style="text-align:justify;line-height:2;">Typically, collections pages don’t tend to get the love or focus they deserve from many eCommerce stores. I can say from experience that collection pages are some of the most visited pages that you’ll see within your eCommerce analytics.They play a major role in overall user experience and visitor/customer product discovery.

Most visitors, especially if they’re new to your store, and regardless of what original acquisition source they came from, will go around and explore the different product options available that you have. It’s completely natural for people who have never come across your site before to explore what else you have on offer (I mean, you most likely do this as well)</p>
</div>


<!--<div class="container-fluid mt-3" style="margin-bottom:100px;">-->
<!--    <div class="row">-->
        {% for i in c %}
<!--        <div class="col-sm-4">-->
            <div class="card" style="width:18rem;">
  <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body">
   <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text"></p>
    <a href="{%url 'shop:allproducts' i.name %} " class="btn btn-primary">Products</a>
  </div>
</div>
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
{% endfor %}

{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid my-5 text-light">
    <div class="row justify-content-center my-2">
        <div class="col-6" >
            {% if d.image %}
            <img class="img-fluid" height="400px" width="500px;" src="{{d.image.url}}">
            {% endif %}
        </div>
        <div class="col-5" style="color:black">
            <p class="display-2 my-2">{{d.name}}</p>
            <p class="lead">{{d.desc}}</p>
            <p class="display-5 my-3">{{d.price}}</p>
            <p class="display-5 my-3">{{d.stock}}</p>

<!--            <p class="display-2 my-2">{{d.category}}</p>-->

            {% if user.is_superuser == True %}
            {% if d.stock == 0 %}

            <div class="text-start">
                <h2>Out of stock</h2>
                <a class="btn btn-danger mt-5" href="{% url 'admin:index' %}">Add stock</a>

              {% else %}
                <h2>Product in stock</h2>
                <a class="btn btn-danger mt-5" href="{% url 'admin:index' %}">Add stock</a>
                {% endif %}
                {% else %}

                {% if d.stock == 0 %}
                <h2>Out of stock</h2>
                {% else %}
                 <a class="btn btn-success mt-5" href="{% url 'cart:addtocart' d.name %}">Add to cart</a>
                {% endif %}
                {% endif %}

            </div>
        </div>
    </div>
</div>


{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3 class="mt-4">Login</h3>
<form method="POST">
{% csrf_token %}
    <div class="mb-3">
  <label class="form-label">UserName</label>
  <input type="text" class="form-control" name="us" placeholder="Enter the username name">
        </div>
    <div class="mb-3">
     <label class="form-label">Password</label>
     <input type="password" class="form-control" name="ps" placeholder="Enter the password">
            </div>

    <div class="mb-3">
             <input type="submit" class="form-control" >
        </div>

</form>
    </center>
{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h4 class="text-center text-success">{{msg}}</h4>
    <h4 class="text-center text-danger">Thank You.....</h4>
    <h4 class="text-center"><a href="{% url 'shop:allcat' %}">Continue Shopping</a></h4>
</div>

{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3 class="mt-4">Order Form</h3>
<form method="POST">
{% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="Enter the address">
        </div>
    <div class="mb-3">
     <label class="form-label">Phone number</label>
     <input type="number" class="form-control" name="p" placeholder="Enter the phone number">
            </div>
    <div class="mb-3">
     <label class="form-label">Account number</label>
     <input type="number" class="form-control" name="n" placeholder="Enter the account number">
            </div>

    <div class="mb-3">
             <input type="submit" class="form-control" >
        </div>

</form>
    </center>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row mt-5">
        <h4 class="text-danger"> Name of the customer:{{u}}</h4>
        {% for i in o %}
        <div class="col-sm-4 mt-3" style="margin-left:100px;">
            <img src="{{i.product.image.url}}" height="200px" width="200px">
        </div>
        <div class="col-sm-6 text-center mt-3">
            <b>Product name:{{i.product.name}}</b><br>
            <b>Product price:{{i.product.price}}</b><br>
            <b>Delivery_address:{{i.address}}</b><br>
            <b>Customer phone:{{i.phone}}</b><br>
            <b>Ordered on:{{i.ordered_date}}</b><br>
            <b class="text-success">Delivery status : {{i.delivery_status}}</b><br>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div>
    <center>
    <img src="{{c.image.url }}" height="400px"; width="300px" style="margin-top:150px;">
    </div>
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h5 class="text-center fw-bold">{{c.name}}</h5>
    <p class="text-align:justify;line-height:2;">{{c.desc}}</p>
</div>
</center>

<!--add cart-->

<div class="container-fluid">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card d-flex flex-column">
                <img src="{{i.image.url}}"  height="200px" width="100%" class="card-img-top" ">
                <div class="card-body">
                    <h5 class="card-title text-center fw-bold" >{{i.name}}</h5>
                    <h5 class="card-title text-center fw-bold">{{i.price}}</h5>
                    <p class="card-text" style="height:250px;" >{{ i.desc }}</p>
                    <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary mt-auto" style="position:relative;left:40%">DETAILS</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<h3 class="mt-4">Register Here</h3>
<form method="POST">
        {% csrf_token %}
    <div class="mb-3">
  <label class="form-label">UserName</label>
  <input type="text" class="form-control" name="us" placeholder="Enter the username name">
        </div>

    <div class="mb-3">
     <label class="form-label">Password</label>
     <input type="password" class="form-control" name="ps" placeholder="Enter the password">
            </div>
    <div class="mb-3">
        <labe class="from-label">Confirmation Password</labe>
        <input type="password" class="form-control" name="cp" placeholder="Enter the confirmation password">
            </div>
     <div class="mb-3">
    <label class="form-label">FirstName</label>
    <input type="text" class="form-control" name="fn" placeholder="Enter the firstusername ">
        </div>

     <div class="mb-3">
    <label class="form-label">LastName</label>
    <input type="text" class="form-control" name="ln" placeholder="Enter the lastname ">
        </div>

    <div class="mb-3">
    <label class="form-label">Email Address</label>
    <input type="email" class="form-control" name="em" placeholder="Enter the email address ">
        </div>

    <div class="mb-3">
             <input type="submit" class="form-control" >
        </div>

</form>

{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Book Search
{% endblock %}

{% block content %}
<center>
<h3 class="mt-4"> You have searched for {{query}}</h3>
    {% if b %}
    <div class="row">
      {% for i in b %}
<div class="col-sm-4 me-2 mb-2">
<div class="card">
    <img src="{{ i.image.url }}" class="card-img-top ">
  <div class="card-body">
    <h5 class="card-title">{{ i.name }}</h5>
    <p class="card-text" ></p>
    <a href="{% url 'shop:detail' i.name %}" class="btn" style="width:100%;">{{ i.name }}</a>
  </div>
</div>
         {% endfor %}
    {% else %}
    <h4>No Result Found</h4>
    {% endif %}
</div>
        </div>
</center>

{% endblock %}